
export type ScreenName = 
  | 'LOGIN' 
  | 'SIGNUP' 
  | 'FORGOT_PASSWORD' 
  | 'VERIFICATION' 
  | 'NEW_PASSWORD' 
  | 'HOME' 
  | 'PROFILE' 
  | 'EDIT_PROFILE'    
  | 'CHANGE_PASSWORD' 
  | 'NOTIFICATION_SETTINGS' 
  | 'CHECK_QUALITY' 
  | 'QUALITY_HISTORY'
  | 'NOTIFICATIONS'
  | 'PARTNER_DASHBOARD'
  | 'PARTNER_INVENTORY'
  | 'TRANSACTIONS'
  | 'UPLOAD_PRODUCT'
  | 'SUCCESS'
  | 'ADMIN_DASHBOARD'
  | 'ADMIN_USERS'
  | 'ADMIN_PRODUCTS'
  | 'ADMIN_REPORTS'
  | 'ADMIN_SETTINGS'
  | 'MAP_VIEW'        
  | 'PARTNER_DETAIL'  
  | 'RESERVATION_FORM' 
  | 'RESERVATION_SUCCESS' 
  | 'IMPACT_REPORT'
  | 'HISTORY'          
  | 'ADD_ADDRESS'
  | 'EXPLORE'          
  | 'LOCATION_SELECT'
  | 'CREATE_REQUEST'
  | 'HELP_FAQ'
  | 'SAVED_ITEMS'
  | 'RATING_HISTORY'
  | 'REPORT_PRODUCT';

export interface User {
  id: string;        // PK (Generated by Backend)
  name: string;      
  email: string;
  avatar: string;
  phone?: string;
  role: 'USER' | 'PARTNER' | 'ADMIN';
  address?: string;  
  ownerName?: string; 
  joinedAt?: string;
  status?: string;   // Added
}

export interface Product {
  id: string; // Changed to string (Backend ID like INV123)
  partnerName: string; 
  partnerAvatar?: string; // Optional (UI helper)
  partnerPhone?: string; // Optional (UI helper)
  name: string;
  description?: string;
  category: string;
  amount: string;     // Changed: Combined string (e.g. "5 Porsi") from Backend
  amountValue?: number; // UI Helper (Parsed)
  amountUnit?: string;  // UI Helper (Parsed)
  price?: string | number; 
  image: string;
  status: 'Buka' | 'Tutup' | 'Habis';
  distance?: string;
  serviceStart?: string; // Optional UI helper
  serviceEnd?: string;   // Optional UI helper
  rating?: number;
  shelfLife?: string;    // Added from backend
  qualityPercentage?: string | number; // Added
  location?: string;     // Added
}

export interface Order {
  id: string;          // Backend ID (TRX...)
  userName: string;    // Backend field
  userEmail: string;   // Backend field
  partner: string;     
  partnerId: string;   
  item: string;        
  itemId: string;      // FK to Product
  quantity: string;
  status: 'Pending' | 'Active' | 'Dikemas' | 'Selesai' | 'Dibatalkan';
  date?: string;       // Timestamp from backend
  pickupCode: string;  // Generated by Backend
  totalPrice?: string;
  deliveryAddress?: string;
  paymentMethod?: string;
}

export interface Review {
  id: string; 
  userEmail: string;
  userName: string;
  partnerId: string;
  partnerName: string;
  itemId: string;
  itemName: string;
  rating: number;
  comment: string;
  timestamp?: string;
}

export interface Report {
  id: string;
  reporterEmail: string;
  reportType: string;
  description: string;
  status: string;
  date?: string;
}

export interface FiturProps {
  navigate: (screen: ScreenName) => void;
  goBack: () => void;
  globalState: any;
  setGlobalState: (key: string, value: any) => void;
  isDarkMode?: boolean;
  toggleTheme?: () => void;
  onLogout?: () => void;
}

export interface Notification {
  id: string;
  userId: string; 
  title: string;
  message: string;
  time?: string;
  type: string;
  isRead: boolean; // Changed from read to isRead
  actionUrl?: string;
}
